# Generated by Django 2.0.7 on 2018-07-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationmodel',
            old_name='numCurrentTest',
            new_name='numConcurrentTest',
        ),
    ]
