# Generated by Django 2.0.7 on 2018-07-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRetrievalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountGuid', models.CharField(max_length=120)),
                ('amountRetrieved', models.IntegerField()),
                ('totalToRetrieve', models.IntegerField()),
            ],
        ),
    ]
