# Generated by Django 2.0.7 on 2018-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyretrievalmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
