# Generated by Django 2.0.7 on 2018-07-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_historyretrievalmodel_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAnalysisResultsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountGuid', models.CharField(max_length=120)),
                ('primaryCurrency', models.CharField(max_length=120)),
                ('secondaryCurrency', models.CharField(max_length=120)),
                ('roi', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BasicAnalysisRunsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountGuid', models.CharField(max_length=120)),
                ('amountRetrieved', models.IntegerField()),
                ('totalToRetrieve', models.IntegerField()),
                ('started', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
