# Generated by Django 2.0.7 on 2018-07-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_basicanalysisresultsmodel_basicanalysisrunsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicanalysisrunsmodel',
            name='botGuid',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
