# Generated by Django 2.0.7 on 2018-07-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_basicanalysisrunsmodel_botguid'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicanalysisrunsmodel',
            name='timeFrameInMinutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
