# Generated by Django 2.0.7 on 2018-07-30 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_basicanalysisrunsmodel_timeframeinminutes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicAnalysisRunsModel',
            new_name='BasicAnalysisRunModel',
        ),
    ]
