# Generated by Django 2.0.7 on 2018-07-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_auto_20180729_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyretrievalmodel',
            name='amountRetrieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historyretrievalmodel',
            name='totalToRetrieve',
            field=models.IntegerField(default=0),
        ),
    ]
