# Generated by Django 2.0.7 on 2018-07-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_basicanalysisrunmodel_iscustombot'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicanalysisresultsmodel',
            name='baseBotGuid',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicanalysisresultsmodel',
            name='isCustomBot',
            field=models.BooleanField(default=False),
        ),
    ]
