# Generated by Django 2.0.7 on 2018-07-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_auto_20180729_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicanalysisresultsmodel',
            name='exchangeName',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
