# Generated by Django 2.0.7 on 2018-07-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_basicanalysisresultsmodel_exchangename'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicanalysisresultsmodel',
            name='baseBotName',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
